# Use root/example as user/password credentials
version: '3.7'

volumes:
    data:

services:

    app:
        build: .
        container_name: email-control-api
        command: npm start
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/app

    mailcatcher:
        image: schickling/mailcatcher
        container_name: myapp-mailcatcher
        ports:
            - 1080:1080
            - 1025:1025

    mongo:
        image: mongo
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        image: mongo-express
        container_name: mongo-web
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
