# Use root/example as user/password credentials
version: '3.7'

volumes:
    data:

services:

    app:
        build: .
        container_name: email-control-api
        command: npm start
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/app

    mailcatcher:
        image: schickling/mailcatcher
        container_name: myapp-mailcatcher
        ports:
            - 1080:1080
            - 1025:1025
