# Use root/example as user/password credentials
version: '3.8'

volumes:
    dbdata-volume:

services:

    app:
        build: .
        container_name: email-control-api
        command: npm start
        ports:
            - "3000:3000"
        links:
            - mongo
        depends_on:
            - mongo
        volumes:
            - .:/usr/app

    mailcatcher:
        image: schickling/mailcatcher
        container_name: myapp-mailcatcher
        ports:
            - 1080:1080
            - 1025:1025

    mongo:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_DATABASE: mail-manager-dev
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - 27017:27017
        volumes:
            - dbdata-volume:/data/db

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - 8081:8081
        links:
            - mongo
        depends_on:
            - mongo
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: senha
            ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017
